packages:
  - 'packages/*'

catalog:
  vue: ^3.5.13
  vue-router: ^4.4.5
  pinia: ^2.2.6
  axios: ^1.3.6
  # vue-i18n: ^9.2.0

  typescript: ^5.7.2
  # eslint
  eslint: ^9.16.0
  eslint-plugin-vue: ^9.32.0
  eslint-plugin-cypress: ^4.1.0
  typescript-eslint: ^8.17.0
  prettier: ^3.4.2

  #
  husky: ^9.1.7
  lint-staged: ^15.2.10
  commitizen: ^4.3.1
  standard-version: ^9.5.0
